### PR TITLE
fix husky initialization step for windows

### LINKED ISSUE #19: [Gulp + Rollup Preset] husky setup fails on windows
Ironically, it seems like the [fix](https://github.com/ghost91-/foundry-factory/pull/7/files#diff-a668b8c71daaa111e957ef5f34c86e690922128b0343920d299324b42654b13b) in #7 broke initializing husky on windows in a different way.

The following is the output:
```
Foundry Factory 0.6.0
? Please select whether to create a module or a system: Module
✔ Created working directory
✔ Initialized new git repository
? Please pick a preset (links point to the documentation of the preset): ghost's Gulp + Rollup Preset
? Check the features needed for your project: TypeScript, Linter & Formatter (ESLint & Prettier)
✔ Created programmatic files
✔ Created files from templates
✔ Created additional directories
✔ Installed dependencies
✖ Failed to execute post installation commands
Failed to create project at C:\devel\fvtt-fantasy-name-generators-2
Error: Command failed: npx husky add .husky/pre-commit \"npx lint-staged\"
```

In both standard cmd and also powershell the following command generates the pre-commit file correctly:  
`npx husky add .husky/pre-commit "npx lint-staged"`
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
```

The escaped quotes do nothing on cmd (husky doesn't understand the arguments), but generates this monstrosity in powershell:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

\\npx lint-staged"
```

### PR DESCRIPTION
**Pull request by OfficerHalf**
Generates the following file with cmd.

`.husky/pre-commit`
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

```

Should compare to what is in a module project generated on unix.

Fixes #19

### CODE REVIEW

**Comment by OfficerHalf** [comment]
Full test was:

1. make change
2. build
3. `cd ..`
4. `node foundry-factory\dist\index.mjs test-dir`
5. Select your module preset
6. Default options
7. See project creation succeeds with no errors

**Comment by ghost91-** [comment]
Thanks, seems to work fine on Linux, could you verify that it also works with `yarn` and `yarn2`? I.e. try
```
node foundry-factory\dist\index.mjs test-dir -m yarn
```
and
```
node foundry-factory\dist\index.mjs test-dir -m yarn2
```

**Comment by ghost91-** [comment]
I also did some checks. For me, your solution fails when using `npm` version `6.14.13` in `cmd`. The steps you describe result in the following error:
```
`C:\Users\Johannes Loher\Development>node foundry-factory\dist\index.mjs test-dir
Foundry Factory 0.6.0
? Please select whether to create a module or a system: Module
√ Created working directory
√ Initialized new git repository
? Please pick a preset (links point to the documentation of the preset): ghost's Gulp + Rollup Preset
? Check the features needed for your project: Linter & Formatter (ESLint & Prettier)
√ Created programmatic files
√ Created files from templates
√ Created additional directories
√ Installed dependencies
× Failed to execute post installation commands
Failed to create project at C:\Users\Johannes Loher\Development\test-dir
Error: Command failed: npx husky add .husky/pre-commit "npx lint-staged"
```
It works fine when using either `yarn`, `yarn2`, or `npm` version `7.16.0`.

My old solution works for `npm` version `6.14.13` but fails for `yarn`, `yarn2`, and `npm` version `7.16.0`.

Version `6` of `npm` is still commonly used as it is the default that is installed with node 14, so we cannot really drop support for it. We need a solution that works for both versions `6`and `7`of `npm` and also for `yarn` and `yarn2`.

**Comment by OfficerHalf** [comment]
Ahh. Weird that they changed handling of things like that, but I guess that counts as a major version breaking change. Will take a look at the npm changelog and see about figuring out the specifics.

**Comment by OfficerHalf** [comment]
Looks like an issue with Husky: https://github.com/typicode/husky/issues/978

**Comment by ghost91-** [comment]
The last comment indicates that it could be fixed by running the `husky` directly with `node` instead of with `npx`:
```
node node_modules\husky\lib\bin.js add .husky/pre-commit "npx lint-staged"
```
or
```
.\node_modules\.bin\husky "npx lint-staged"
```
should probably work...

**Comment by ghost91-** [comment]
Fixed in #25

**Pull request closed without merging**
